FROM node:20-alpine

# Instalar pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# Copiar archivos de dependencia de la raíz (workspace)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copiar los package.json de todos los servicios para que pnpm instale todo junto
COPY backend/auth-service/package.json ./backend/auth-service/
COPY backend/movie-service/package.json ./backend/movie-service/
COPY backend/review-service/package.json ./backend/review-service/
COPY backend/watchlist-service/package.json ./backend/watchlist-service/

# Instalar todas las dependencias en modo producción
RUN pnpm install --prod

# Copiar todo el código fuente del proyecto
COPY . .

# Variables de entorno para producción
ENV NODE_ENV=production
ENV PORT=10000

# Exponer el puerto de Render
EXPOSE 10000

# Comando para arrancar el monolito (archivo index.js de la raíz)
CMD ["node", "index.js"]
